import React,{useState,useMemo} from 'react';import {NavLink,Outlet,useNavigate,useLocation} from 'react-router-dom';import {motion,AnimatePresence} from 'framer-motion';
import {Cake,Heart,Settings,Search,Bell,ChevronDown,Menu,X,User,LogOut,Sun} from 'lucide-react';
import '../../styles/admin-theme.css';
import Sidebar from './Sidebar';
import { signOutAdmin } from '../../services/adminAuth';
import useDropdown from '../../hooks/useOutside';import {useApp} from '../../context/AppContext';
import {Avatar,Toasts,ConfirmDialog,EmptyState} from '../ui';import {daysUntil,rel,today} from '../../utils/dates';
function SearchBox(){const {customers}=useApp();const [q,setQ]=useState('');const d=useDropdown();const nv=useNavigate();const searchRef=React.useRef(null);
 React.useEffect(()=>{const focusSearch=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();searchRef.current?.focus()}};window.addEventListener('keydown',focusSearch);return()=>window.removeEventListener('keydown',focusSearch)},[]);
 const res=useMemo(()=>{const term=q.trim().toLowerCase();return term?customers.filter(c=>[c.name,c.phone,c.email].join(' ').toLowerCase().includes(term)||(term.includes('birth')&&c.birthday)||(term.includes('anniversary')&&c.anniversary)).slice(0,6):[]},[q,customers]);
 return <div className="ac-search-box relative flex-1 max-w-xs" ref={d.ref}><Search size={16} className="ac-search-icon absolute left-3 top-3 text-muted"/><input ref={searchRef} value={q} onChange={e=>{setQ(e.target.value);d.setOpen(true)}} onFocus={()=>d.setOpen(true)} placeholder="Search customers, events…" aria-label="Search customers and events" className="ac-search-input inp !pl-9 !pr-16 !rounded-full"/><kbd className="ac-search-shortcut">Ctrl + K</kbd>
 {d.open&&q.trim()&&<div className="absolute top-12 left-0 right-0 min-w-[16rem] bg-paper border border-beige rounded-xl shadow-lg p-1 z-40">{res.length?res.map(c=><button key={c.id} onClick={()=>{nv(`/admin/customers/${c.id}`);setQ('');d.setOpen(false)}} className="w-full flex items-center gap-3 p-2 rounded-lg hover:bg-beige text-left"><Avatar name={c.name} photo={c.photo} size={32}/><span className="text-sm"><b className="block font-medium">{c.name}</b><span className="text-xs text-muted">{c.phone}</span></span></button>):<EmptyState title="No customers found" text={`Nothing matches “${q}”.`}/>}</div>}</div>}
function Bell_(){const {customers}=useApp();const d=useDropdown();const nv=useNavigate();const [read,setRead]=useState(false);const [gone,setGone]=useState([]);
 const items=useMemo(()=>{const a=[];customers.forEach(c=>{const b=daysUntil(c.birthday),n=daysUntil(c.anniversary);if(b!=null&&b<=7)a.push({id:c.id+'b',t:`${c.name}'s birthday — ${rel(b).toLowerCase()}`,id2:c.id,I:Cake,k:b});if(n!=null&&n<=7)a.push({id:c.id+'a',t:`${c.name}'s anniversary — ${rel(n).toLowerCase()}`,id2:c.id,I:Heart,k:n})});return a.sort((x,y)=>x.k-y.k).filter(x=>!gone.includes(x.id))},[customers,gone]);
 const count=read?0:Math.min(items.length,9);
 return <div className="relative" ref={d.ref}><button aria-label="Notifications" onClick={()=>d.setOpen(!d.open)} className="ac-notification-button relative p-2.5 rounded-full hover:bg-beige"><Bell size={20} strokeWidth={1.75}/>{count>0&&<span className="absolute top-1 right-1 min-w-4 h-4 px-1 rounded-full bg-burg text-white text-[10px] flex items-center justify-center">{count}</span>}</button>
 <AnimatePresence>{d.open&&<motion.div initial={{opacity:0,y:-6}} animate={{opacity:1,y:0}} exit={{opacity:0}} className="absolute right-0 top-12 w-80 max-w-[calc(100vw-2rem)] bg-paper border border-beige rounded-xl shadow-lg z-40"><div className="flex items-center justify-between p-3 border-b border-beige"><b className="h-serif">Notifications</b><div className="flex gap-3 text-xs text-warm"><button onClick={()=>setRead(true)}>Mark all read</button><button onClick={()=>setGone(items.map(i=>i.id))}>Clear</button></div></div>
 <div className="max-h-80 overflow-y-auto p-1">{items.length?items.map(i=><div key={i.id} className="flex items-center gap-1 rounded-lg hover:bg-beige"><button onClick={()=>{nv(`/admin/customers/${i.id2}`);d.setOpen(false)}} className="flex-1 flex items-center gap-3 p-2 text-left text-sm"><span className="w-8 h-8 rounded-full bg-peach flex items-center justify-center text-warm"><i.I size={15}/></span>{i.t}</button><button aria-label="Dismiss" className="p-2" onClick={()=>setGone(g=>[...g,i.id])}><X size={14}/></button></div>):<EmptyState title="All caught up" text="No new notifications."/>}</div></motion.div>}</AnimatePresence></div>}
function Header({onMenu}){const {settings,adminUser}=useApp();const d=useDropdown();const nv=useNavigate();const h=new Date().getHours();const g=h<12?'morning':h<17?'afternoon':'evening';
 return <header className="ac-topbar sticky top-0 z-30 h-[68px] bg-paper/95 border-b border-beige flex items-center gap-3 px-4 md:px-6"><button aria-label="Toggle sidebar" onClick={onMenu} className="ac-menu-toggle p-2 rounded-lg hover:bg-beige"><Menu size={22}/></button>
 <div className="ac-greeting hidden lg:block border-l border-beige pl-4 mr-auto"><div className="h-serif text-base font-semibold flex items-center gap-2"><Sun size={16} className="text-gold"/>Good {g}, {settings.name}!</div><div className="text-xs text-muted">Here's what's happening at Alchemist today.</div></div>
 <div className="flex-1 lg:flex-none flex justify-end"><SearchBox/></div><Bell_/>
 <div className="ac-user-control relative" ref={d.ref}><button onClick={()=>d.setOpen(!d.open)} className="flex items-center gap-2 pl-2"><Avatar name={settings.name} size={34} tone="bg-coffee text-ivory"/><span className="hidden md:block text-left"><b className="block text-sm font-medium">{settings.name}</b><span className="text-xs text-muted">{settings.email||adminUser?.email}</span></span><ChevronDown size={16} className="hidden md:block"/></button>
 <AnimatePresence>{d.open&&<motion.div initial={{opacity:0,y:-6}} animate={{opacity:1,y:0}} exit={{opacity:0}} className="absolute right-0 top-12 w-48 bg-paper border border-beige rounded-xl shadow-lg p-1 text-sm z-40">
 {[['Profile','/admin/settings?tab=profile',User],['Settings','/admin/settings',Settings]].map(([l,to,I])=><button key={l} onClick={()=>{nv(to);d.setOpen(false)}} className="w-full flex items-center gap-2 px-3 h-10 rounded-lg hover:bg-beige"><I size={16}/>{l}</button>)}
 <button onClick={()=>{d.setOpen(false);document.dispatchEvent(new CustomEvent('alc-logout'))}} className="w-full flex items-center gap-2 px-3 h-10 rounded-lg hover:bg-beige text-burg"><LogOut size={16}/>Logout</button></motion.div>}</AnimatePresence></div></header>}
export default function Layout(){const {toasts,closeToast,confirm,setConfirm,toast}=useApp();const [open,setOpen]=useState(false);const [collapsed,setCollapsed]=useState(false);const loc=useLocation();const nv=useNavigate();
 React.useEffect(()=>{const f=()=>setConfirm({title:'Log out?',message:'You will be signed out of the administrator account.',confirmLabel:'Log out',onConfirm:async()=>{try{await signOutAdmin();nv('/admin/login',{replace:true})}catch(error){toast(`Could not sign out: ${error.message}`,'error')}}});document.addEventListener('alc-logout',f);return()=>document.removeEventListener('alc-logout',f)},[nv,setConfirm,toast]);
 const toggle=()=>window.innerWidth>=1024?setCollapsed(c=>!c):setOpen(o=>!o);
 return <div className="ac-app min-h-full flex">
 {!collapsed&&<aside className="ac-sidebar hidden lg:block w-60 shrink-0 sticky top-0 h-screen"><Sidebar/></aside>}
 <AnimatePresence>{open&&<><motion.div className="ac-mobile-scrim fixed inset-0 bg-dark/50 z-40 lg:hidden" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setOpen(false)}/><motion.aside className="ac-mobile-drawer fixed inset-y-0 left-0 w-64 z-50 lg:hidden" initial={{x:-260}} animate={{x:0}} exit={{x:-260}} transition={{type:'tween',duration:.22}}><Sidebar onNavigate={()=>setOpen(false)}/></motion.aside></>}</AnimatePresence>
 <div className="ac-content flex-1 min-w-0"><Header onMenu={toggle}/><motion.main key={loc.pathname} initial={{opacity:0,y:6}} animate={{opacity:1,y:0}} className="ac-main p-4 md:p-8 max-w-[1400px] mx-auto"><Outlet/></motion.main></div>
 <Toasts toasts={toasts} onClose={closeToast}/><ConfirmDialog data={confirm} onClose={()=>setConfirm(null)}/></div>}
