import React,{useState} from 'react';import {useParams,useNavigate} from 'react-router-dom';import {ArrowLeft,Pencil,Trash2,Phone,Mail,Cake,Heart,CalendarPlus,StickyNote,Activity} from 'lucide-react';
import {useApp} from '../context/AppContext';import {Avatar,Badge,EmptyState} from '../components/ui';import CustomerForm from '../components/customers/CustomerForm';import {fmtFull} from '../utils/dates';
const Row=({I,l,v})=><div className="flex items-start gap-3 py-2"><span className="w-8 h-8 rounded-full bg-beige flex items-center justify-center text-warm shrink-0"><I size={15}/></span><div><div className="text-xs text-muted">{l}</div><div className="text-sm break-all">{v||'—'}</div></div></div>;
const Box=({title,children,cls=''})=><section className={`card p-5 ${cls}`}><h2 className="h-serif text-lg mb-2">{title}</h2>{children}</section>;
export default function CustomerProfile(){const {id}=useParams();const {customers,removeCustomer,setConfirm}=useApp();const nv=useNavigate();const [edit,setEdit]=useState(false);const c=customers.find(x=>x.id===id);
 if(!c)return <EmptyState title="Customer not found" text="This customer may have been deleted." action={<button className="btn-primary" onClick={()=>nv('/admin/customers')}>Back to Customers</button>}/>;
 const del=()=>setConfirm({title:'Delete customer?',message:`${c.name} will be permanently removed.`,confirmLabel:'Delete',onConfirm:async()=>{try{await removeCustomer(c.id);nv('/admin/customers')}catch{}}});
 return <div className="ac-customer-profile"><button className="btn-ghost mb-4" onClick={()=>nv(-1)}><ArrowLeft size={16}/>Back</button>
 <div className="card p-5 flex flex-wrap items-center gap-4 mb-4"><Avatar name={c.name} photo={c.photo} size={64} tone="bg-coffee text-ivory"/><div className="flex-1 min-w-[180px]"><h1 className="h-serif text-3xl font-semibold">{c.name}</h1><div className="mt-1"><Badge status={c.status}/></div></div>
 <div className="flex flex-wrap gap-2"><button className="btn-primary" onClick={()=>setEdit(true)}><Pencil size={15}/>Edit Customer</button><button className="btn-danger" onClick={del}><Trash2 size={15}/>Delete Customer</button><button className="btn-ghost" onClick={()=>nv('/admin/customers')}>Back to Customers</button></div></div>
 <div className="grid md:grid-cols-3 gap-4"><Box title="Contact Information"><Row I={Phone} l="Phone" v={c.phone}/><Row I={Mail} l="Email" v={c.email}/></Box>
 <Box title="Personal Information"><Row I={Cake} l="Birthday" v={fmtFull(c.birthday)}/><Row I={Heart} l="Anniversary" v={fmtFull(c.anniversary)}/></Box>
 <Box title="Customer Information"><Row I={CalendarPlus} l="Joined" v={fmtFull(c.joinedAt)}/><div className="pt-1"><Badge status={c.status}/></div></Box>
 <Box title="Notes" cls="md:col-span-1"><p className="text-sm text-char/80 flex gap-2"><StickyNote size={16} className="shrink-0 mt-0.5 text-gold"/>{c.notes||'No notes yet.'}</p></Box>
 <Box title="Activity" cls="md:col-span-2"><ol className="relative border-l border-beige ml-2 space-y-4 mt-3">{c.activity.map(a=><li key={a.id} className="ml-5"><span className="absolute -left-[7px] w-3.5 h-3.5 rounded-full bg-gold border-2 border-paper"/><div className="text-sm flex items-center gap-2"><Activity size={13} className="text-warm"/>{a.text}</div><div className="text-xs text-muted">{fmtFull(a.date)}</div></li>)}</ol></Box></div>
 <CustomerForm open={edit} customer={c} onClose={()=>setEdit(false)}/></div>}
