import React,{useMemo,useState,useEffect} from 'react';import {useNavigate,useSearchParams} from 'react-router-dom';import {Plus,Search,Eye,Pencil,Trash2,ArrowUpDown,X,Mail,Phone,Cake,Heart,Users} from 'lucide-react';
import {useApp} from '../context/AppContext';import {PageHeader,Avatar,Badge,EmptyState,Pagination} from '../components/ui';import CustomerForm from '../components/customers/CustomerForm';import {fmtShort,iso,MONTHS} from '../utils/dates';
const SIZE=6;
export default function Customers(){const {customers,customersLoading,removeCustomer,setConfirm}=useApp();const nv=useNavigate();const [searchParams,setSearchParams]=useSearchParams();const joined=searchParams.get('joined');const joinedMonth=searchParams.get('joinedMonth');const today=iso(new Date());const dateFilter=joined==='today'?'Today\'s new customers':joinedMonth?`Customers added in ${MONTHS[Number(joinedMonth.slice(5,7))-1]} ${joinedMonth.slice(0,4)}`:'';
 const [q,setQ]=useState('');const [st,setSt]=useState('All');const [sort,setSort]=useState({k:'name',dir:1});const [page,setPage]=useState(1);const [form,setForm]=useState({open:false,c:null});
 const rows=useMemo(()=>{let r=customers.filter(c=>(st==='All'||c.status===st)&&[c.name,c.phone,c.email].join(' ').toLowerCase().includes(q.toLowerCase())&&(joined==='today'?c.joinedAt===today:joinedMonth?c.joinedAt?.startsWith(joinedMonth):true));return r.sort((a,b)=>String(a[sort.k]||'').localeCompare(String(b[sort.k]||''))*sort.dir)},[customers,q,st,sort,joined,joinedMonth,today]);
 const pages=Math.max(1,Math.ceil(rows.length/SIZE));useEffect(()=>{if(page>pages)setPage(pages)},[pages,page]);useEffect(()=>setPage(1),[q,st,joined,joinedMonth]);
 const view=rows.slice((page-1)*SIZE,page*SIZE);const dirty=q||st!=='All'||joined||joinedMonth;
 const del=c=>setConfirm({title:'Delete customer?',message:`${c.name} will be permanently removed.`,confirmLabel:'Delete',onConfirm:async()=>{try{await removeCustomer(c.id)}catch{}}});
 const Th=({k,children})=><th className="text-left font-medium px-4 py-3"><button className="inline-flex items-center gap-1 hover:text-coffee" onClick={()=>setSort(s=>({k,dir:s.k===k?-s.dir:1}))}>{children}<ArrowUpDown size={12}/></button></th>;
 const Acts=({c})=><div className="flex gap-1"><button aria-label="View" title="View" onClick={()=>nv(`/admin/customers/${c.id}`)} className="p-2 rounded-lg hover:bg-beige"><Eye size={16}/></button><button aria-label="Edit" title="Edit" onClick={()=>setForm({open:true,c})} className="p-2 rounded-lg hover:bg-beige"><Pencil size={16}/></button><button aria-label="Delete" title="Delete" onClick={()=>del(c)} className="p-2 rounded-lg hover:bg-rose text-burg"><Trash2 size={16}/></button></div>;
 return <div className="ac-customers"><PageHeader icon={Users} title="Customers" subtitle={dateFilter||"Manage your Alchemist customer community."}><button className="btn-primary" onClick={()=>setForm({open:true,c:null})}><Plus size={16}/>Add Customer</button></PageHeader>
 <div className="ac-customer-toolbar flex flex-wrap gap-2 mb-4"><div className="relative flex-1 min-w-[200px] max-w-sm"><Search size={16} className="absolute left-3 top-3 text-muted"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, phone, email" aria-label="Search customers" className="inp !pl-9"/></div>
 <select aria-label="Filter by status" value={st} onChange={e=>setSt(e.target.value)} className="inp !w-auto"><option value="All">All statuses</option><option>Active</option><option>New</option><option>Pending</option></select>{dirty&&<button className="btn-ghost" onClick={()=>{setQ('');setSt('All');setSearchParams({})}}><X size={15}/>Clear filters</button>}</div>
 <div className="ac-customer-table card overflow-hidden">{customersLoading&&!customers.length?<EmptyState title="Loading customers" text="Fetching customer records from Supabase…"/>:!view.length?<EmptyState title="No customers found" text="Try a different search or clear your filters." action={<button className="btn-primary" onClick={()=>{setQ('');setSt('All')}}>Clear filters</button>}/>:<>
 <table className="hidden md:table w-full text-sm"><thead className="bg-ivory text-muted text-xs uppercase tracking-wide"><tr><Th k="name">Customer</Th><th className="text-left px-4 py-3 font-medium">Contact</th><Th k="birthday">Birthday</Th><Th k="anniversary">Anniversary</Th><Th k="status">Status</Th><th className="px-4 py-3 text-left font-medium">Actions</th></tr></thead>
 <tbody className="divide-y divide-beige">{view.map(c=><tr key={c.id} className="hover:bg-ivory"><td className="px-4 py-3"><button onClick={()=>nv(`/admin/customers/${c.id}`)} className="flex items-center gap-3 text-left"><Avatar name={c.name} photo={c.photo} size={36}/><b className="font-medium">{c.name}</b></button></td><td className="px-4 py-3"><div>{c.phone}</div><div className="text-xs text-muted">{c.email}</div></td><td className="px-4 py-3">{fmtShort(c.birthday)}</td><td className="px-4 py-3">{fmtShort(c.anniversary)}</td><td className="px-4 py-3"><Badge status={c.status}/></td><td className="px-4 py-3"><Acts c={c}/></td></tr>)}</tbody></table>
 <div className="ac-mobile-customer-list md:hidden divide-y divide-beige">{view.map(c=><div key={c.id} className="p-4"><div className="flex items-center gap-3"><Avatar name={c.name} photo={c.photo} size={42}/><div className="flex-1 min-w-0"><button onClick={()=>nv(`/admin/customers/${c.id}`)} className="font-medium">{c.name}</button></div><Badge status={c.status}/></div><div className="mt-2 text-xs text-muted flex gap-4"><span className="flex items-center gap-1"><Phone size={12}/>{c.phone}</span><span className="flex items-center gap-1"><Mail size={12}/>{c.email}</span></div><div className="mt-2 flex items-center justify-between"><span className="text-xs flex items-center gap-3"><span className="flex items-center gap-1"><Cake size={12}/>{fmtShort(c.birthday)}</span><span className="flex items-center gap-1"><Heart size={12}/>{fmtShort(c.anniversary)}</span></span><Acts c={c}/></div></div>)}</div>
 <Pagination page={page} pages={pages} onChange={setPage} total={rows.length}/></>}</div>
 <CustomerForm open={form.open} customer={form.c} onClose={()=>setForm({open:false,c:null})}/></div>}
