import React,{useMemo,useState} from 'react';import {useNavigate,Link} from 'react-router-dom';import {motion} from 'framer-motion';import {Users,CalendarCheck,UserPlus,Cake,Heart,ChevronRight,ArrowRight,Calendar,Home,Leaf} from 'lucide-react';
import {AreaChart,Area,XAxis,YAxis,Tooltip,CartesianGrid,ResponsiveContainer} from 'recharts';
import {useApp} from '../context/AppContext';import {Avatar,Badge,PageHeader,EmptyState} from '../components/ui';import {MONTHS,iso,monthOf,yearOf,fmtFull,fmtShort,daysUntil} from '../utils/dates';
const StatCard=({i,label,value,sub,Icon,tone,to})=>{const nv=useNavigate();return <motion.button type="button" aria-label={`${label}: ${value}`} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:i*.05}} whileHover={{y:-3}} onClick={()=>nv(to)} className={`ac-stat-card cursor-pointer text-left rounded-2xl border border-beige p-5 shadow-card ${tone[0]}`}><Icon className="ac-stat-watermark" size={138} strokeWidth={1.1} aria-hidden="true"/><div className="ac-stat-card-heading flex items-center gap-3"><span className={`ac-stat-icon w-11 h-11 rounded-full flex items-center justify-center ${tone[1]}`}><Icon size={28} strokeWidth={1.75}/></span><span className="ac-stat-label text-sm text-char/80 flex-1">{label}</span></div><div className="ac-stat-number font-serif text-4xl mt-3 text-coffee">{value}</div>{sub&&<div className="ac-stat-support text-xs text-muted mt-1">{sub}</div>}<span className="ac-stat-arrow" aria-hidden="true"><ArrowRight size={17}/></span></motion.button>};
const Card=({title,sub,to,icon,children,className=''})=><section className={`ac-panel card p-5 ${className}`}><div className="flex items-start justify-between mb-3"><div className="flex items-center gap-3">{icon}<div><h2 className="h-serif text-xl">{title}</h2>{sub&&<p className="text-xs text-muted">{sub}</p>}</div></div>{to&&<Link to={to} className="ac-text-link text-sm text-coffee flex items-center gap-1 hover:underline">View all<ArrowRight size={14}/></Link>}</div>{children}</section>;
const maskPhone=phone=>{const digits=String(phone||'').replace(/\D/g,'');return digits.length>=12?`+${digits.slice(0,2)} ${digits.slice(2,7)}****`:digits?`${digits.slice(0,5)}****`:'—'};

function UpcomingCustomers({customers,type}){
 const birthday=type==='birthday';const title=birthday?'Upcoming birthdays':'Upcoming anniversaries';const subtitle=birthday?'Customers celebrating this week':'Keep track of meaningful moments';const Icon=birthday?Cake:Heart;const route=birthday?'/admin/birthdays':'/admin/anniversaries';
 const navigate=useNavigate();const rows=customers.filter(c=>c[type]).map(c=>({...c,days:daysUntil(c[type])})).filter(c=>c.days>=0&&c.days<=14).sort((a,b)=>a.days-b.days).slice(0,3);
 return <Card title={title} sub={subtitle} to={route} icon={<span className={`ac-event-heading-icon ${birthday?'ac-event-heading-birthday':'ac-event-heading-anniversary'}`}><Icon size={20} strokeWidth={1.8}/></span>} className="ac-dashboard-events">
  {rows.length?<div className="divide-y divide-beige">{rows.map(c=>{const relative=birthday?(c.days===0?'Birthday today':c.days===1?'Birthday tomorrow':`In ${c.days} days`):(c.days===0?'Today':`In ${c.days} days`);const tone=c.days<=1?'soon':c.days<=7?'near':'later';return <button key={c.id} onClick={()=>navigate(`/admin/customers/${c.id}`)} className="ac-dashboard-event-row w-full flex items-center gap-3 text-left"><Avatar name={c.name} photo={c.photo} size={30}/><b className="flex-1 min-w-0 truncate">{c.name}</b><span className={`ac-event-time ac-event-time-${tone}`}>{relative}</span><span className="ac-event-date">{fmtShort(c[type])}</span><ChevronRight size={15} className="text-muted"/></button>})}</div>:<EmptyState title={`No upcoming ${birthday?'birthdays':'anniversaries'}`} text="There are no customer dates in the next two weeks."/>}
 </Card>;
};

export default function Dashboard(){
 const {customers}=useApp();const navigate=useNavigate();const now=new Date();
 const months=useMemo(()=>Array.from({length:12},(_,i)=>{const d=new Date(now.getFullYear(),now.getMonth()-i,1);return {v:`${d.getFullYear()}-${d.getMonth()}`,l:`${MONTHS[d.getMonth()].slice(0,3)} ${d.getFullYear()}`,y:d.getFullYear(),m:d.getMonth()}}),[]);
 const [sel,setSel]=useState(months[0].v);const cur=months.find(m=>m.v===sel);const [year,setYear]=useState(now.getFullYear());const t=iso(now);
 const stats={total:customers.length,today:customers.filter(c=>c.joinedAt===t).length,added:customers.filter(c=>yearOf(c.joinedAt)===cur.y&&monthOf(c.joinedAt)===cur.m).length,bd:customers.filter(c=>monthOf(c.birthday)===cur.m).length,an:customers.filter(c=>monthOf(c.anniversary)===cur.m).length};
 const prior=new Date(cur.y,cur.m-1,1);const priorCount=customers.filter(c=>yearOf(c.joinedAt)===prior.getFullYear()&&monthOf(c.joinedAt)===prior.getMonth()).length;const pct=priorCount?Math.round((stats.added-priorCount)/priorCount*100):stats.added?100:0;
 const years=[...new Set([now.getFullYear(),...customers.map(c=>yearOf(c.joinedAt))])].sort((a,b)=>b-a).slice(0,2);
 const growth=useMemo(()=>MONTHS.slice(1).map((m,i)=>({m:m.slice(0,3),n:customers.filter(c=>yearOf(c.joinedAt)===year&&monthOf(c.joinedAt)===i+1).length})),[customers,year]);
 const recent=[...customers].sort((a,b)=>b.joinedAt.localeCompare(a.joinedAt)).slice(0,4);
 return <div className="ac-dashboard"><div className="ac-dashboard-head"><div className="ac-dashboard-breadcrumb"><Home size={14}/><ChevronRight size={13}/><span>Dashboard</span></div><PageHeader title="Dashboard" subtitle="An overview of your customer community."><div className="ac-month-control relative"><Calendar size={16} className="absolute left-3 top-3 text-warm"/><select aria-label="Select month" value={sel} onChange={e=>setSel(e.target.value)} className="inp !pl-9 !w-auto">{months.map(m=><option key={m.v} value={m.v}>{m.l}</option>)}</select></div></PageHeader><aside className="ac-dashboard-quote"><Leaf size={42} aria-hidden="true"/><span>“Better connections,<br/>create better experiences.”</span></aside></div>
 <div className="ac-stat-grid grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-5 gap-4">
 <StatCard i={0} label="Total Customers" value={stats.total} sub={<><strong>↑ {pct}%</strong> vs. last month</>} Icon={Users} tone={['bg-gradient-to-br from-paper to-beige/60','bg-beige text-coffee']} to="/admin/customers"/>
 <StatCard i={1} label="New Today" value={stats.today} sub={stats.today?'Joined today':'No new'} Icon={CalendarCheck} tone={['bg-sgreen/60','bg-sgreen text-[#2f6b3a]']} to="/admin/customers?joined=today"/>
 <StatCard i={2} label="Added This Month" value={stats.added} sub={stats.added?cur.l:'No new'} Icon={UserPlus} tone={['bg-beige/50','bg-gold/25 text-coffee']} to={`/admin/customers?joinedMonth=${cur.y}-${String(cur.m+1).padStart(2,'0')}`}/>
 <StatCard i={3} label="Birthdays This Month" value={stats.bd} Icon={Cake} tone={['bg-peach/70','bg-peach text-[#9a5a2e]']} to="/admin/birthdays"/>
 <StatCard i={4} label="Anniversaries This Month" value={stats.an} Icon={Heart} tone={['bg-rose/70','bg-rose text-burg']} to="/admin/anniversaries"/></div>
 <div className="ac-dashboard-mid-grid grid lg:grid-cols-5 gap-4 mt-4"><section className="ac-chart-panel card p-5 lg:col-span-3"><div className="flex items-start justify-between"><div><h2 className="h-serif text-xl">Customer Growth</h2><p className="text-xs text-muted">Monthly customer registrations</p></div><select aria-label="Select year" value={year} onChange={e=>setYear(+e.target.value)} className="inp !w-auto">{years.map(y=><option key={y} value={y}>{y}</option>)}</select></div>
 <div className="ac-chart-plot h-64 mt-4"><ResponsiveContainer><AreaChart data={growth} margin={{left:-20,right:8}}><defs><linearGradient id="customer-growth-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#2F6FED" stopOpacity={.22}/><stop offset="100%" stopColor="#DBEAFE" stopOpacity={.04}/></linearGradient></defs><CartesianGrid stroke="#E6ECF7" strokeDasharray="2 4"/><XAxis dataKey="m" tick={{fontSize:11,fill:'#6B7A99'}} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} tick={{fontSize:11,fill:'#6B7A99'}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{borderRadius:12,border:'1px solid #E6ECF7',fontSize:12,background:'#fff',boxShadow:'0 8px 24px rgba(37,99,235,.1)'}} formatter={v=>[`${v} Customers`,'']} labelFormatter={l=>`${l} ${year}`}/><Area type="monotone" dataKey="n" stroke="#2F6FED" strokeWidth={2} fill="url(#customer-growth-fill)" dot={{r:3,fill:'#2F6FED'}}/></AreaChart></ResponsiveContainer></div></section>
 <Card title="Recent customers" to="/admin/customers" className="ac-recent-customers lg:col-span-2"><div className="divide-y divide-beige">{recent.map(c=><button key={c.id} onClick={()=>navigate(`/admin/customers/${c.id}`)} className="ac-recent-row w-full flex items-center gap-3 py-1.5 text-left hover:bg-ivory rounded-lg px-1"><Avatar name={c.name} photo={c.photo} size={30}/><span className="flex-1 min-w-0"><b className="block text-sm font-medium truncate">{c.name}</b><span className="ac-recent-phone text-xs text-muted">{maskPhone(c.phone)}</span></span><span className="text-right"><span className="block text-xs text-muted">{fmtFull(c.joinedAt)}</span><Badge status={c.status}/></span><ChevronRight size={15} className="text-muted"/></button>)}</div></Card></div>
 <div className="ac-dashboard-bottom-grid grid lg:grid-cols-2 gap-4 mt-4"><UpcomingCustomers customers={customers} type="birthday"/><UpcomingCustomers customers={customers} type="anniversary"/></div></div>;
}
