import React,{useMemo,useState} from 'react';import {useNavigate} from 'react-router-dom';import {Search,Cake,Heart,ChevronRight,Eye,Gift} from 'lucide-react';
import {useApp} from '../context/AppContext';import {PageHeader,Avatar,Pill,EmptyState} from '../components/ui';import {years,MONTHS,daysUntil,monthOf,rel,fmtShort,fmtFull} from '../utils/dates';
const CFG={birthday:{title:'Birthdays',sub:'Celebrate every special moment with your customers.',I:Cake,chip:'bg-peach text-[#9a5a2e]',ring:'bg-peach text-[#9a5a2e]'},anniversary:{title:'Anniversaries',sub:'Keep track of meaningful customer milestones.',I:Heart,chip:'bg-rose text-burg',ring:'bg-rose text-burg'}};
export default function Events({type}){const {customers}=useApp();const nv=useNavigate();const C=CFG[type];const [m,setM]=useState('all');const [q,setQ]=useState('');const [f,setF]=useState('all');
 const items=useMemo(()=>customers.filter(c=>c[type]).map(c=>({...c,days:daysUntil(c[type])})).filter(c=>(m==='all'||monthOf(c[type])===+m)&&[c.name,c.phone,c.email].join(' ').toLowerCase().includes(q.toLowerCase())&&(f==='all'||c.days<=30)).sort((a,b)=>a.days-b.days),[customers,type,m,q,f]);
 const secs=[['Today',items.filter(i=>i.days===0)],['This Week',items.filter(i=>i.days>0&&i.days<=7)],['Upcoming',items.filter(i=>i.days>7)]];
 return <div className={`ac-events ac-events-${type}`}><PageHeader icon={C.I} title={C.title} subtitle={C.sub}/><div className="ac-event-art" aria-hidden="true"><span>Happy {type==='birthday'?'Birthday!':'Anniversary!'}</span><C.I size={56} strokeWidth={1.6}/><i/><i/><i/><i/><i/></div>
 <div className="ac-event-toolbar flex flex-wrap gap-2 mb-6"><div className="relative flex-1 min-w-[200px] max-w-sm"><Search size={16} className="absolute left-3 top-3 text-muted"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by name, phone, email…" aria-label="Search" className="inp !pl-9"/></div>
 <select aria-label="Month" value={m} onChange={e=>setM(e.target.value)} className="inp !w-auto"><option value="all">All months</option>{MONTHS.map((n,i)=><option key={n} value={i}>{n}</option>)}</select>
 <div className="flex rounded-xl border border-beige overflow-hidden">{[['all',`All ${C.title.toLowerCase()}`],['up','Upcoming (30 days)']].map(([k,l])=><button key={k} onClick={()=>setF(k)} className={`px-4 h-10 text-sm ${f===k?'bg-coffee text-ivory':'bg-paper hover:bg-beige/60'}`}>{l}</button>)}</div></div>
 {!items.length?<div className="card"><EmptyState title={`No ${C.title.toLowerCase()} found`} text="Try another month or clear the search." action={<button className="btn-primary" onClick={()=>{setM('all');setQ('');setF('all')}}>Reset filters</button>}/></div>:
 <div className="ac-event-layout"><div className="ac-event-table-wrap card"><div className="overflow-x-auto"><table className="ac-event-table w-full text-sm"><thead><tr><th>Customer</th><th>Phone</th><th>Email</th><th>{type==='birthday'?'Birthday':'Anniversary Date'}</th><th>{type==='birthday'?'Age':'Years'}</th><th>Status</th><th>Actions</th></tr></thead>
 {secs.map(([t,list])=>list.length>0&&<tbody key={t}><tr className="ac-event-group"><th colSpan="7">{t} <span>({list.length})</span></th></tr>{list.map(c=><tr key={c.id}><td><button className="ac-event-customer" onClick={()=>nv(`/admin/customers/${c.id}`)}><Avatar name={c.name} photo={c.photo} size={40} tone={C.ring}/><span>{c.name}</span></button></td><td>{c.phone}</td><td>{c.email}</td><td>{fmtShort(c[type])}</td><td>{type==='birthday'?years(c.birthday):years(c.anniversary)}</td><td><Pill tone={c.days===0?'ac-rel-today':'ac-rel-date'}>{c.days===0?'Today':rel(c.days)}</Pill></td><td><button aria-label={`View ${c.name}`} title="View customer" onClick={()=>nv(`/admin/customers/${c.id}`)} className="ac-row-action"><Eye size={17}/></button></td></tr>)}</tbody>)}
 </table></div></div><aside className="ac-event-rail">{type==='birthday'&&items.some(c=>c.days===0)&&<section className="ac-event-feature"><h2>Today’s Birthday</h2>{items.filter(c=>c.days===0).slice(0,1).map(c=><button key={c.id} onClick={()=>nv(`/admin/customers/${c.id}`)}><Avatar name={c.name} photo={c.photo} size={52} tone={C.ring}/><span><b>{c.name}</b><small>{fmtFull(c.birthday)} · Age {years(c.birthday)}</small></span></button>)}</section>}<section className="ac-event-upcoming"><h2>{type==='birthday'?'Upcoming Birthdays':'Upcoming Anniversaries'}</h2>{items.filter(c=>c.days>0).slice(0,4).map(c=><button key={c.id} onClick={()=>nv(`/admin/customers/${c.id}`)}><Avatar name={c.name} photo={c.photo} size={36} tone={C.ring}/><span><b>{c.name}</b><small>{fmtShort(c[type])}</small></span><Pill tone="ac-rel-date">In {c.days} days</Pill></button>)}</section>{type==='anniversary'&&<section className="ac-event-promo"><span><b>Special Moments<br/>Make Stronger Bonds</b><small>Let’s make their day even more memorable!</small></span><Gift size={44}/></section>}</aside></div>}</div>}
