import React,{useState,useEffect} from 'react';import {useSearchParams} from 'react-router-dom';import {useForm} from 'react-hook-form';import {zodResolver} from '@hookform/resolvers/zod';import {z} from 'zod';import {User,Bell,Palette,Store,Shield,Settings as SettingsIcon} from 'lucide-react';
import {useApp} from '../context/AppContext';import {PageHeader,Field,Toggle} from '../components/ui';
import {changeAdminPassword} from '../services/adminAuth';
const TABS=[['profile','Profile',User],['notifications','Notifications',Bell],['appearance','Appearance',Palette],['workspace','Workspace Settings',Store],['security','Security',Shield]];
const pSchema=z.object({name:z.string().trim().min(2,'Name is required'),email:z.string().email('Enter a valid email'),phone:z.string().regex(/^\+?[0-9 ()-]{8,16}$/,'Enter a valid phone number')});
const wSchema=z.object({cafe:z.string().trim().min(2,'Required'),hours:z.string().trim().min(3,'Required'),address:z.string().trim().min(5,'Required')});
const sSchema=z.object({current:z.string().min(1,'Current password is required'),next:z.string().min(8,'At least 8 characters').regex(/[0-9]/,'Include a number'),confirm:z.string()}).refine(d=>d.next===d.confirm,{path:['confirm'],message:'Passwords do not match'});
const Row=({t,d,children})=><div className="ac-setting-row flex items-center justify-between gap-4 py-4 border-b border-beige last:border-0"><div><div className="text-sm font-medium">{t}</div><div className="text-xs text-muted">{d}</div></div>{children}</div>;
export default function Settings(){const [sp,setSp]=useSearchParams();const tab=TABS.some(t=>t[0]===sp.get('tab'))?sp.get('tab'):'profile';const {settings,setSettings,toast}=useApp();
 const P=useForm({resolver:zodResolver(pSchema),defaultValues:{name:settings.name,email:settings.email,phone:settings.phone}});
 const W=useForm({resolver:zodResolver(wSchema),defaultValues:settings.workspace||{cafe:'Alchemist – The Lake View Café',hours:'8:00 AM – 10:00 PM',address:'Lakeside Road, Salem'}});
 const S=useForm({resolver:zodResolver(sSchema),defaultValues:{current:'',next:'',confirm:''}});
 const updatePassword=async({current,next})=>{try{await changeAdminPassword(current,next);S.reset();toast('Password updated successfully')}catch(error){toast(`Could not update password: ${error.message}`,'error')}};
 const nt=(k,v)=>{setSettings(s=>({...s,notif:{...s.notif,[k]:v}}));toast('Settings saved successfully')};
 return <div className="ac-settings"><PageHeader icon={SettingsIcon} title="Settings" subtitle="Manage your profile, preferences and workspace."/>
 <div className="ac-settings-layout grid md:grid-cols-[220px_1fr] gap-6"><nav className="ac-settings-tabs card p-2 flex md:flex-col gap-1 overflow-x-auto h-fit">{TABS.map(([k,l,I])=><button key={k} onClick={()=>setSp({tab:k})} className={`flex items-center gap-2 px-3 h-10 rounded-xl text-sm whitespace-nowrap ${tab===k?'bg-coffee text-ivory':'hover:bg-beige/60'}`}><I size={16}/>{l}</button>)}</nav>
 <div className="ac-settings-content card p-6 max-w-2xl">
 {tab==='profile'&&<form className="space-y-4" noValidate onSubmit={P.handleSubmit(d=>{setSettings(s=>({...s,...d}));toast('Settings saved successfully')})}><h2 className="h-serif text-xl">Profile</h2><Field label="Name" error={P.formState.errors.name?.message}><input className="inp" {...P.register('name')}/></Field><Field label="Email" error={P.formState.errors.email?.message}><input className="inp" {...P.register('email')}/></Field><Field label="Phone" error={P.formState.errors.phone?.message}><input className="inp" {...P.register('phone')}/></Field><button className="btn-primary">Save changes</button></form>}
 {tab==='notifications'&&<div><h2 className="h-serif text-xl mb-2">Notifications</h2>{[['birthday','Birthday reminders','Get reminded before customer birthdays'],['anniversary','Anniversary reminders','Get reminded of upcoming anniversaries'],['newCustomer','New customer notifications','When a customer is added'],['system','System notifications','Product updates and maintenance']].map(([k,t,d])=><Row key={k} t={t} d={d}><Toggle label={t} checked={settings.notif[k]} onChange={v=>nt(k,v)}/></Row>)}</div>}
 {tab==='appearance'&&<div><h2 className="h-serif text-xl mb-2">Appearance</h2><Row t="Light mode" d="The Alchemist workspace uses a warm light theme."><Toggle label="Light mode" checked onChange={()=>toast('Light mode is always on')}/></Row><Row t="Compact mode" d="Slightly smaller text and spacing."><Toggle label="Compact mode" checked={!!settings.compact} onChange={v=>{setSettings(s=>({...s,compact:v}));toast('Settings saved successfully')}}/></Row></div>}
 {tab==='workspace'&&<form className="space-y-4" noValidate onSubmit={W.handleSubmit(d=>{setSettings(s=>({...s,workspace:d}));toast('Settings saved successfully')})}><h2 className="h-serif text-xl">Workspace Settings</h2><Field label="Café name" error={W.formState.errors.cafe?.message}><input className="inp" {...W.register('cafe')}/></Field><Field label="Opening hours" error={W.formState.errors.hours?.message}><input className="inp" {...W.register('hours')}/></Field><Field label="Address" error={W.formState.errors.address?.message}><input className="inp" {...W.register('address')}/></Field><button className="btn-primary">Save changes</button></form>}
 {tab==='security'&&<form className="space-y-4" noValidate onSubmit={S.handleSubmit(updatePassword)}><h2 className="h-serif text-xl">Change password</h2>{[['current','Current password'],['next','New password'],['confirm','Confirm password']].map(([k,l])=><Field key={k} label={l} error={S.formState.errors[k]?.message}><input type="password" autoComplete="off" className="inp" {...S.register(k)}/></Field>)}<button className="btn-primary" disabled={S.formState.isSubmitting}>{S.formState.isSubmitting?'Updating…':'Update password'}</button></form>}
 </div></div></div>}
