import React,{useState} from 'react';import {motion,AnimatePresence} from 'framer-motion';import {X,ChevronLeft,ChevronRight,CheckCircle2,AlertCircle,SearchX} from 'lucide-react';import {initials} from '../../utils/dates';
export const Avatar=({name,photo,size=40,tone='bg-beige text-coffee'})=>{const [bad,setBad]=useState(false);const st={width:size,height:size,fontSize:size*.36};
 const avatarTone=['ac-avatar-blue','ac-avatar-green','ac-avatar-lavender','ac-avatar-peach','ac-avatar-pink'][(name?.charCodeAt(0)||0)%5];
 if(photo&&!bad)return <img src={photo} alt={name} style={{width:size,height:size}} onError={()=>setBad(true)} className="ac-avatar-image shrink-0 rounded-full object-cover ring-2 ring-paper shadow-sm bg-beige"/>;
 return <span style={st} className={`ac-avatar shrink-0 inline-flex items-center justify-center rounded-full font-semibold ${avatarTone} ${tone}`}>{initials(name)}</span>};
const B={Active:'bg-sgreen text-[#2f6b3a]',New:'bg-sgreen text-[#2f6b3a]',Pending:'bg-peach text-[#9a5a2e]'};
export const Badge=({status,className=''})=><span className={`ac-status inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium ${B[status]||'bg-beige text-coffee'} ${className}`}><i className="w-1.5 h-1.5 rounded-full bg-current"/>{status}</span>;
export const Pill=({children,tone='bg-peach text-[#9a5a2e]'})=><span className={`ac-pill px-3 py-1 rounded-full text-xs font-medium whitespace-nowrap ${tone}`}>{children}</span>;
export function PageHeader({title,subtitle,children,icon:Icon}){return <div className="ac-page-header flex flex-wrap items-end justify-between gap-4 mb-6"><div className="ac-page-heading">{Icon&&<span className="ac-page-icon"><Icon size={22} strokeWidth={1.8}/></span>}<div className="ac-page-copy"><h1 className="h-serif text-3xl md:text-4xl">{title}</h1><p className="text-muted mt-1">{subtitle}</p><div className="ac-page-accent mt-3 h-0.5 w-12 bg-gold"/></div></div><div className="ac-page-actions flex items-center gap-2">{children}</div></div>}
export function Modal({open,onClose,title,children,width='max-w-2xl'}){return <AnimatePresence>{open&&<motion.div className="ac-modal-overlay fixed inset-0 z-50 flex items-end sm:items-center justify-center p-0 sm:p-4" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}>
 <div className="absolute inset-0 bg-dark/40" onClick={onClose}/>
 <motion.div role="dialog" aria-modal="true" initial={{y:24,opacity:0}} animate={{y:0,opacity:1}} exit={{y:24,opacity:0}} className={`ac-modal-card relative bg-paper w-full ${width} max-h-[92vh] overflow-y-auto rounded-t-2xl sm:rounded-2xl border border-beige shadow-xl`}>
 <div className="flex items-center justify-between px-6 pt-5 pb-3"><h2 className="h-serif text-2xl">{title}</h2><button aria-label="Close" onClick={onClose} className="p-2 rounded-lg hover:bg-beige"><X size={18}/></button></div><div className="px-6 pb-6">{children}</div></motion.div></motion.div>}</AnimatePresence>}
export function ConfirmDialog({data,onClose}){return <Modal open={!!data} onClose={onClose} title={data?.title||''} width="max-w-md"><p className="text-muted text-sm mb-6">{data?.message}</p><div className="flex justify-end gap-2"><button className="btn-ghost" onClick={onClose}>Cancel</button><button className="btn-danger" onClick={()=>{data.onConfirm();onClose()}}>{data?.confirmLabel||'Confirm'}</button></div></Modal>}
export const EmptyState=({title='Nothing found',text='Try adjusting your search or filters.',action})=><div className="text-center py-12 px-4"><div className="mx-auto w-12 h-12 rounded-full bg-beige flex items-center justify-center text-warm mb-3"><SearchX size={22}/></div><h3 className="h-serif text-lg">{title}</h3><p className="text-sm text-muted mt-1">{text}</p>{action&&<div className="mt-4">{action}</div>}</div>;
export function Toasts({toasts,onClose}){return <div className="fixed top-4 right-4 z-[60] space-y-2 w-[calc(100%-2rem)] sm:w-80"><AnimatePresence>{toasts.map(t=><motion.div key={t.id} layout initial={{opacity:0,x:40}} animate={{opacity:1,x:0}} exit={{opacity:0,x:40}} className="flex items-center gap-3 bg-paper border border-beige rounded-xl shadow-lg px-4 py-3 text-sm">{t.type==='error'?<AlertCircle size={18} className="text-burg"/>:<CheckCircle2 size={18} className="text-[#2f6b3a]"/>}<span className="flex-1">{t.msg}</span><button aria-label="Dismiss" onClick={()=>onClose(t.id)}><X size={15}/></button></motion.div>)}</AnimatePresence></div>}
export const Toggle=({checked,onChange,label})=><button role="switch" aria-checked={checked} aria-label={label} onClick={()=>onChange(!checked)} className={`w-11 h-6 rounded-full p-0.5 transition ${checked?'bg-coffee':'bg-beige'}`}><span className={`block w-5 h-5 rounded-full bg-white shadow transition ${checked?'translate-x-5':''}`}/></button>;
export function Pagination({page,pages,onChange,total}){if(pages<=1)return null;return <div className="ac-pagination flex items-center justify-between px-4 py-3 border-t border-beige text-sm"><span className="text-muted">{total} customers</span><div className="flex items-center gap-1"><button aria-label="Previous page" disabled={page===1} onClick={()=>onChange(page-1)} className="btn-ghost !h-9 !px-2"><ChevronLeft size={16}/></button>{Array.from({length:pages},(_,i)=><button key={i} aria-current={page===i+1?'page':undefined} onClick={()=>onChange(i+1)} className={`h-9 w-9 rounded-xl text-sm ${page===i+1?'bg-coffee text-ivory':'hover:bg-beige'}`}>{i+1}</button>)}<button aria-label="Next page" disabled={page===pages} onClick={()=>onChange(page+1)} className="btn-ghost !h-9 !px-2"><ChevronRight size={16}/></button></div></div>}
export const Field=({label,error,children})=><div><label className="lbl">{label}</label>{children}{error&&<p className="err">{error}</p>}</div>;
